"""Interactive local interface for configurable Causal Attitude Network analyses.

Run from the repository root with:
    streamlit run app/app.py
"""

from __future__ import annotations

import hashlib
import io
import json
import re
import shutil
import subprocess
import sys
import time
import uuid
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import streamlit as st
import yaml

from abadi_study2_replication import render_abadi_study2_replication
from ess_cronos3_sogreen_case import render_ess_cronos3_sogreen_case

ROOT = Path(__file__).resolve().parents[1]
RUNS_DIR = ROOT / "user_runs"
R_AVAILABLE = shutil.which("Rscript") is not None
ALLOWED_SUFFIXES = {".csv", ".xlsx", ".xls"}
DOMAIN_OPTIONS = [
    "Beliefs",
    "Evaluations",
    "Expected outcomes",
    "Feelings",
    "Behaviour",
    "Risk appraisal",
    "Governance",
    "Context",
    "Other",
]


@st.cache_data(show_spinner=False)
def workbook_sheets(file_bytes: bytes) -> list[str]:
    return pd.ExcelFile(io.BytesIO(file_bytes)).sheet_names


@st.cache_data(show_spinner=False)
def read_uploaded_data(file_bytes: bytes, filename: str, sheet: str | None) -> pd.DataFrame:
    suffix = Path(filename).suffix.lower()
    if suffix == ".csv":
        return pd.read_csv(io.BytesIO(file_bytes))
    return pd.read_excel(io.BytesIO(file_bytes), sheet_name=sheet or 0)


def display_name(variable: str) -> str:
    return re.sub(r"[_\-.]+", " ", str(variable)).strip().title()


def profile_variables(data: pd.DataFrame) -> pd.DataFrame:
    records: list[dict[str, Any]] = []
    for column in data.columns:
        series = data[column]
        numeric = pd.api.types.is_numeric_dtype(series)
        nonmissing = int(series.notna().sum())
        unique = int(series.nunique(dropna=True))
        values = pd.to_numeric(series, errors="coerce") if not numeric else series
        integer_like = bool(numeric and series.dropna().map(lambda value: float(value).is_integer()).all()) if nonmissing else False
        likely_ordinal = bool(numeric and integer_like and 2 <= unique <= 7)
        records.append(
            {
                "variable": str(column),
                "dtype": str(series.dtype),
                "nonmissing": nonmissing,
                "missing_pct": round(float(series.isna().mean() * 100), 2),
                "unique": unique,
                "numeric": numeric,
                "likely_ordinal": likely_ordinal,
                "min": float(values.min()) if numeric and nonmissing else np.nan,
                "max": float(values.max()) if numeric and nonmissing else np.nan,
            }
        )
    return pd.DataFrame.from_records(records)


def candidate_labels(variables: list[str]) -> dict[str, str]:
    return {variable: display_name(variable) for variable in variables}


def parse_filter_value(value: str) -> Any:
    stripped = value.strip()
    if not stripped:
        return ""
    try:
        numeric = float(stripped)
        return int(numeric) if numeric.is_integer() else numeric
    except ValueError:
        return stripped


def select_study2_workspace() -> None:
    st.session_state["workspace_selector"] = "Abadi et al. Study 2 replication"


def design_interpretive_notice(study_design: str) -> str:
    if study_design == "Cross-sectional survey":
        return (
            "The uploaded study is marked as cross-sectional. Undirected network edges are conditional "
            "associations and do not establish directional causal effects."
        )
    if study_design == "Longitudinal or panel study":
        return (
            "The uploaded study is marked as longitudinal or panel. The current workflow estimates "
            "cross-sectional network structures; temporal or within-person claims require a pre-specified "
            "longitudinal model and design-appropriate analysis."
        )
    if study_design == "Experimental or quasi-experimental study":
        return (
            "The uploaded study is marked as experimental or quasi-experimental. The current workflow "
            "summarizes network structure; causal claims depend on the assignment mechanism, intervention "
            "fidelity, and a design-appropriate estimand."
        )
    return "Study design has not been specified. The app will not assign a causal interpretation to network estimates."


def restore_config_to_state(config: dict[str, Any]) -> None:
    """Restore mapping widgets from a configuration generated by this app.

    The uploaded data file is intentionally not restored: participants re-upload it
    locally, while the YAML restores all analytical choices made in mapping-only mode.
    """
    project = config.get("project", {})
    sample_filter = config.get("sample", {}).get("filter", {})
    variables = config.get("variables", {})
    network = config.get("network", {})
    comparisons = config.get("comparisons", {})

    st.session_state["project_title"] = str(project.get("title", "User-supplied CAN analysis"))
    st.session_state["study_design"] = str(project.get("study_design", "Not specified"))
    st.session_state["filter_variable"] = str(sample_filter.get("variable", "") or "— none —")
    st.session_state["filter_operator"] = str(sample_filter.get("operator", "equals"))
    st.session_state["filter_value_text"] = str(sample_filter.get("value", "") or "")
    st.session_state["country_variable"] = str(variables.get("country", "") or "— none —")
    st.session_state["use_variable"] = str(variables.get("use_frequency", "") or "— none —")
    st.session_state["node_type"] = str(network.get("node_type", "ordinal"))
    st.session_state["levels"] = int(network.get("node_levels", 5))
    st.session_state["node_ids"] = [str(node["id"]) for node in network.get("nodes", []) if "id" in node]
    for node in network.get("nodes", []):
        if "id" in node:
            variable = str(node["id"])
            st.session_state[f"label_{variable}"] = str(node.get("label", display_name(variable)))
            st.session_state[f"domain_{variable}"] = str(node.get("domain", "Beliefs"))

    factor_models = config.get("factor_models", [])
    st.session_state["factor_items"] = [str(item) for item in (factor_models[0].get("items", []) if factor_models else [])]
    st.session_state["categorical_variables"] = [str(item) for item in config.get("contextual_associations", {}).get("categorical_variables", [])]
    country = comparisons.get("country", {})
    st.session_state["country_minimum_n"] = int(country.get("minimum_n", 500))
    st.session_state["quick_mode"] = int(config.get("bootstrapping", {}).get("edge_bootstrap_iterations", 250)) <= 25


def build_config(
    *,
    run_dir: Path,
    data_path: Path,
    sheet: str | None,
    project_title: str,
    study_design: str,
    node_mapping: list[dict[str, str]],
    node_type: str,
    levels: int,
    filter_variable: str,
    filter_operator: str,
    filter_value: Any,
    country_variable: str,
    use_variable: str,
    categorical_variables: list[str],
    factor_items: list[str],
    country_minimum_n: int,
    quick_mode: bool,
) -> dict[str, Any]:
    node_ids = [entry["id"] for entry in node_mapping]
    factor_models: list[dict[str, Any]] = []
    if len(factor_items) >= 3:
        factor_models.append(
            {
                "id": "user_selected_scale",
                "label": "User-selected candidate scale",
                "items": factor_items,
                "estimator": "MLR",
                "minimum_cfi": 0.90,
                "maximum_rmsea": 0.08,
                "country_invariance": bool(country_variable),
            }
        )

    iterations = 25 if quick_mode else 250
    nct_iterations = 25 if quick_mode else 100
    config: dict[str, Any] = {
        "project": {
            "id": re.sub(r"[^a-z0-9_]+", "_", project_title.lower()).strip("_") or "user_can_analysis",
            "title": project_title,
            "seed": 20260818,
            "study_design": study_design,
            "interpretive_notice": design_interpretive_notice(study_design),
        },
        "input": {
            "path": str(data_path.resolve()),
            "sheet": sheet or "Sheet1",
            "format": data_path.suffix.lower().lstrip("."),
            "questionnaire": "",
            "source_doi": "",
            "source_license": "User supplied",
        },
        "audit": {"mardia_max_n": 2000},
        "sample": {
            "filter": {
                "variable": filter_variable,
                "operator": filter_operator,
                "value": filter_value,
                "label": "User-defined analysis filter" if filter_variable else "No filter",
            },
            "complete_case_primary_network": True,
        },
        "variables": {
            "country": country_variable,
            "language": "",
            "study_field": "",
            "gender": "",
            "age": "",
            "use_frequency": use_variable,
            "use_experience": "",
        },
        "network": {
            "estimator": "mgm",
            "regularization": "LASSO",
            "model_selection": "EBIC",
            "ebic_gamma": 0.25,
            "node_type": node_type,
            "node_levels": int(levels),
            "nodes": node_mapping,
        },
        "factor_models": factor_models,
        "bootstrapping": {
            "edge_bootstrap_iterations": iterations,
            "case_drop_bootstrap_iterations": iterations,
            "case_drop_proportions": [0.05, 0.10, 0.25, 0.50, 0.75],
        },
        "community_detection": {"primary_algorithm": "walktrap", "bootstrap_consensus_iterations": 10 if quick_mode else 100},
        "comparisons": {
            "split_sample": {"enabled": True, "proportion_first_sample": 0.50, "label": "Random split-sample methodological check"},
            "use_frequency_median_split": {
                "enabled": bool(use_variable),
                "variable": use_variable,
                "exclude_from_network": True,
                "label": "User-selected median-split comparison",
            },
            "country": {
                "enabled": bool(country_variable),
                "variable": country_variable,
                "minimum_n": int(country_minimum_n),
                "network_estimator": "ggm_spearman",
                "all_pairwise_nct": True,
                "nct_iterations": nct_iterations,
                "p_adjustments": ["bonferroni", "fdr"],
            },
            "networktree": {"enabled": bool(country_variable or use_variable), "moderators": [item for item in [country_variable, use_variable] if item]},
        },
        "contextual_associations": {"categorical_variables": categorical_variables, "effect_size": "cramers_v"},
        "output": {
            "computations_dir": str((run_dir / "outputs").resolve()),
            "figures_dir": str((run_dir / "figures").resolve()),
            "report_dir": str((run_dir / "report").resolve()),
            "save_rds": True,
            "save_csv": True,
            "figure_width": 14,
            "figure_height": 11,
            "figure_dpi": 180,
        },
    }
    # The implemented high/low comparison cannot use its grouping variable as a network node.
    if use_variable in node_ids:
        config["comparisons"]["use_frequency_median_split"]["enabled"] = False
    return config


def eligibility_table(
    data: pd.DataFrame,
    profile: pd.DataFrame,
    node_ids: list[str],
    country_variable: str,
    use_variable: str,
    factor_items: list[str],
    country_minimum_n: int,
) -> pd.DataFrame:
    numeric_nodes = set(profile.loc[profile["numeric"], "variable"].astype(str))
    selected = data.loc[:, node_ids] if node_ids else pd.DataFrame(index=data.index)
    complete_n = int(selected.dropna().shape[0]) if node_ids else 0
    all_numeric = set(node_ids).issubset(numeric_nodes)
    country_groups = 0
    eligible_countries = 0
    if country_variable:
        country_counts = data[country_variable].dropna().value_counts()
        country_groups = int(country_counts.size)
        eligible_countries = int((country_counts >= country_minimum_n).sum())

    rows = [
        {
            "Abadi-style computation": "Data audit and complete-case flow",
            "Status": "Ready" if len(node_ids) >= 3 else "Placeholder",
            "Requirement / action": "Map at least three distinct item-level nodes.",
        },
        {
            "Abadi-style computation": "Abadi joint mixed graphical network (MGM, LASSO/EBIC)",
            "Status": "Ready" if len(node_ids) >= 3 and all_numeric and complete_n >= max(100, len(node_ids) * 10) else "Not yet eligible",
            "Requirement / action": f"Mapped nodes: {len(node_ids)}; complete cases: {complete_n}; numeric coding: {'yes' if all_numeric else 'no'}. Numeric coding and an adequate complete-case sample are required.",
        },
        {
            "Abadi-style computation": "Centrality, edge accuracy, case-drop stability, and Walktrap communities",
            "Status": "Ready (time-intensive)" if len(node_ids) >= 3 and all_numeric and complete_n >= max(100, len(node_ids) * 10) else "Placeholder",
            "Requirement / action": "Requires an eligible core network. Bootstrap iterations are adjustable through Quick versus Full mode.",
        },
        {
            "Abadi-style computation": "CFA, country CFA, EFA, and measurement invariance",
            "Status": "Ready" if len(factor_items) >= 3 and set(factor_items).issubset(numeric_nodes) else "Placeholder",
            "Requirement / action": "Select at least three theoretically coherent numeric items for a candidate scale. Country invariance additionally needs a country variable and adequate country samples.",
        },
        {
            "Abadi-style computation": "Two-study network comparison (original-paper design)",
            "Status": "Placeholder",
            "Requirement / action": "Requires two independent, comparable studies or waves. The current runner offers a labelled random split-sample methodological check, not a substitute for a second study.",
        },
        {
            "Abadi-style computation": "High/low group networks and NCT",
            "Status": "Ready" if use_variable and use_variable not in node_ids and len(node_ids) >= 3 and all_numeric else "Placeholder",
            "Requirement / action": "Choose a numeric grouping variable that is not included as a network node. The current generic implementation uses a median split.",
        },
        {
            "Abadi-style computation": "Country networks, pairwise NCT, and edge-matrix correlations",
            "Status": "Ready (time-intensive)" if eligible_countries >= 2 and len(node_ids) >= 3 and all_numeric else "Placeholder",
            "Requirement / action": f"Eligible country groups at n ≥ {country_minimum_n}: {eligible_countries}. At least two are needed.",
        },
        {
            "Abadi-style computation": "Country-network clustering and pooled cluster networks",
            "Status": "Ready" if eligible_countries >= 2 and len(node_ids) >= 3 and all_numeric else "Placeholder",
            "Requirement / action": "Requires at least two eligible country networks; three or more groups are preferable for meaningful clustering.",
        },
        {
            "Abadi-style computation": "NetworkTree moderation",
            "Status": "Optional placeholder",
            "Requirement / action": "Requires suitable categorical moderators and the optional R package `NetworkTree`; the app records an explicit status rather than silently omitting this module.",
        },
        {
            "Abadi-style computation": "Categorical association checks (chi-square and Cramér’s V)",
            "Status": "Ready" if len([column for column in profile["variable"].astype(str) if column not in numeric_nodes]) >= 2 else "Placeholder",
            "Requirement / action": "Requires at least two categorical variables selected for contextual checks.",
        },
    ]
    return pd.DataFrame(rows)


def write_run_bundle(uploaded_bytes: bytes, uploaded_name: str, config: dict[str, Any], data_preview: pd.DataFrame) -> tuple[Path, Path]:
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    run_id = f"run_{time.strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:8]}"
    run_dir = RUNS_DIR / run_id
    raw_dir = run_dir / "raw_data"
    raw_dir.mkdir(parents=True, exist_ok=False)
    data_path = raw_dir / Path(uploaded_name).name
    data_path.write_bytes(uploaded_bytes)
    config_path = run_dir / "config.yml"
    config_path.write_text(yaml.safe_dump(config, sort_keys=False, allow_unicode=True), encoding="utf-8")
    profile = profile_variables(data_preview)
    profile.to_csv(run_dir / "variable_profile.csv", index=False)
    manifest = {
        "run_id": run_id,
        "created_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "source_filename": Path(uploaded_name).name,
        "source_sha256": hashlib.sha256(uploaded_bytes).hexdigest(),
        "rows": int(data_preview.shape[0]),
        "columns": int(data_preview.shape[1]),
        "configuration": str(config_path),
    }
    (run_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return run_dir, config_path


def invoke_r(script_name: str, config_path: Path) -> tuple[int, str]:
    command = ["Rscript", "--vanilla", str(ROOT / "scripts" / script_name), "--config", str(config_path)]
    completed = subprocess.run(command, cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=60 * 60)
    return completed.returncode, completed.stdout


st.set_page_config(page_title="CAN Models", page_icon="◌", layout="wide")
st.title("CAN Models")
st.caption("A reproducible Causal Attitude Network workspace with an original-data Abadi et al. Study 2 replication, an ESS CRONOS-3 Wave 6 Green Transition Attitude Network under a publication gate, and a bring-your-own-data workflow.")

workspace = st.radio(
    "Choose a workspace",
    ["Abadi et al. Study 2 replication", "ESS CRONOS-3 / SoGreen Wave 6", "Bring your own data"],
    horizontal=True,
    label_visibility="collapsed",
    key="workspace_selector",
)
if workspace == "Abadi et al. Study 2 replication":
    render_abadi_study2_replication()
    st.stop()
if workspace == "ESS CRONOS-3 / SoGreen Wave 6":
    render_ess_cronos3_sogreen_case()
    st.stop()
st.header("Bring your own data")
st.caption("Upload a compatible survey, map its variable names to CAN roles, inspect the available computations, and create a reproducible run bundle.")

for state_key, default_value in {
    "quick_mode": True,
    "filter_operator": "equals",
    "filter_value_text": "",
    "country_minimum_n": 500,
    "node_type": "ordinal",
    "levels": 5,
    "project_title": "User-supplied CAN analysis",
}.items():
    if state_key not in st.session_state:
        st.session_state[state_key] = default_value

with st.sidebar:
    st.button(
        "← Return to Study 2 replication",
        on_click=select_study2_workspace,
        use_container_width=True,
        help="Return to the original-data Abadi et al. Study 2 replication workspace.",
    )
    st.divider()
    st.header("1. Upload data")
    uploaded = st.file_uploader("CSV or Excel workbook", type=["csv", "xlsx", "xls"], help="Upload one row per participant. The file is stored only in a local run directory when you choose to create a run bundle.")
    saved_mapping = st.file_uploader(
        "Optional saved CAN YAML configuration",
        type=["yml", "yaml"],
        help="Upload a configuration previously downloaded from this app to restore its filter, node mapping, domains, and analysis settings.",
    )
    if saved_mapping is not None and st.button("Restore saved mapping", use_container_width=True):
        try:
            restored = yaml.safe_load(saved_mapping.getvalue().decode("utf-8"))
            if not isinstance(restored, dict) or "network" not in restored:
                raise ValueError("The file is not a CAN Models YAML configuration.")
            restore_config_to_state(restored)
            st.rerun()
        except Exception as error:
            st.error(f"Could not restore the YAML configuration: {error}")
    study_design = st.selectbox(
        "Study design",
        [
            "Not specified",
            "Cross-sectional survey",
            "Longitudinal or panel study",
            "Experimental or quasi-experimental study",
        ],
        help="This optional selection records the study design in the configuration and controls the interpretation guidance shown after data upload.",
        key="study_design",
    )
    quick_mode = st.toggle("Quick mode", key="quick_mode", help="Uses fewer bootstrap and permutation iterations for feasibility checks. Full mode retains the larger configured analysis settings.")

if uploaded is None:
    st.info("Upload a CSV or Excel file to begin mapping your variables. No fixed variable names are required.")
    st.stop()

file_bytes = uploaded.getvalue()
suffix = Path(uploaded.name).suffix.lower()
if suffix not in ALLOWED_SUFFIXES:
    st.error("Please upload a CSV, XLSX, or XLS file.")
    st.stop()

sheet = None
if suffix in {".xlsx", ".xls"}:
    sheets = workbook_sheets(file_bytes)
    sheet = st.sidebar.selectbox("Worksheet", sheets)

try:
    data = read_uploaded_data(file_bytes, uploaded.name, sheet)
except Exception as error:
    st.error(f"The file could not be read: {error}")
    st.stop()

if data.empty:
    st.error("The uploaded dataset has no rows.")
    st.stop()

data.columns = [str(column) for column in data.columns]
profile = profile_variables(data)
variables = profile["variable"].astype(str).tolist()
placeholder = "— none —"
# Keep restored values valid for the currently uploaded file; incompatible fields
# fall back to an empty mapping rather than causing a Streamlit widget error.
if "node_ids" not in st.session_state:
    st.session_state["node_ids"] = variables[: min(8, len(variables))]
else:
    st.session_state["node_ids"] = [item for item in st.session_state["node_ids"] if item in variables]
for state_key in ["filter_variable", "country_variable", "use_variable"]:
    if state_key in st.session_state and st.session_state[state_key] not in variables + [placeholder]:
        st.session_state[state_key] = placeholder
for state_key in ["factor_items", "categorical_variables"]:
    if state_key in st.session_state:
        st.session_state[state_key] = [item for item in st.session_state[state_key] if item in variables]

st.subheader("Data preview")
left, right = st.columns([2, 1])
with left:
    st.dataframe(data.head(20), width="stretch", height=300)
with right:
    st.metric("Rows", f"{len(data):,}")
    st.metric("Variables", f"{len(data.columns):,}")
    st.metric("File", uploaded.name)

with st.expander("Variable profile and coding check", expanded=True):
    st.dataframe(profile, width="stretch", height=350)
    st.caption("The current R workflow expects numeric codes for network nodes. Categorical text labels should be recoded before estimation; their variable names can still be mapped here without requiring any predefined naming convention.")

if study_design != "Not specified":
    with st.expander("Interpretation guidance for the selected study design", expanded=False):
        st.info(design_interpretive_notice(study_design))

st.header("2. Map your data to CAN roles")
st.write("Select item-level survey variables as network nodes. The labels and theoretical domains below are displayed in output figures and never need to match the raw column names.")
node_ids = st.multiselect("Network-node variables", variables, key="node_ids", help="Select at least three numeric item-level variables. Avoid composite scores unless they are theoretically intended as a node.")
node_mapping: list[dict[str, str]] = []
if node_ids:
    for index, variable in enumerate(node_ids):
        label_key = f"label_{variable}"
        domain_key = f"domain_{variable}"
        if label_key not in st.session_state:
            st.session_state[label_key] = display_name(variable)
        if domain_key not in st.session_state:
            st.session_state[domain_key] = "Beliefs"
        columns = st.columns([3, 3, 2])
        with columns[0]:
            label = st.text_input(f"Label for {variable}", key=label_key)
        with columns[1]:
            domain = st.selectbox(f"CAN domain for {variable}", DOMAIN_OPTIONS, key=domain_key)
        with columns[2]:
            st.caption(f"Source\n`{variable}`")
        node_mapping.append({"id": variable, "label": label, "domain": domain})

mapping_columns = st.columns(3)
with mapping_columns[0]:
    filter_variable = st.selectbox("Optional analysis filter", [placeholder] + variables, key="filter_variable", help="For example, select a prior-use variable and specify the response code to define the analytic sample.")
    filter_operator = st.selectbox("Filter operator", ["equals", "not_equals", "in"], key="filter_operator")
    filter_value_text = st.text_input("Filter value", value="", key="filter_value_text")
with mapping_columns[1]:
    country_variable = st.selectbox("Optional country/group variable", [placeholder] + variables, key="country_variable", help="Enables country-specific networks and country-comparison eligibility checks.")
    country_minimum_n = st.number_input("Minimum cases per country/group", min_value=50, max_value=5000, step=50, key="country_minimum_n")
with mapping_columns[2]:
    use_variable = st.selectbox("Optional numeric high/low grouping variable", [placeholder] + variables, key="use_variable", help="Used for the implemented median-split comparison. It must not also remain in the compared network.")
    node_type = st.selectbox("Common node type", ["ordinal", "continuous"], key="node_type")
    levels = st.number_input("Ordinal response levels", min_value=2, max_value=20, step=1, key="levels", disabled=node_type != "ordinal")

factor_items = st.multiselect("Optional candidate factor/CFA scale", node_ids, key="factor_items", help="Select three or more coherent items only when a latent scale is theoretically justified. This activates CFA/EFA and, with country groups, invariance checks.")
categorical_options = profile.loc[~profile["numeric"], "variable"].astype(str).tolist()
categorical_variables = st.multiselect("Categorical variables for contextual association checks", categorical_options, key="categorical_variables", help="Selecting two or more variables enables chi-square and Cramér’s V outputs.")

filter_variable = "" if filter_variable == placeholder else filter_variable
country_variable = "" if country_variable == placeholder else country_variable
use_variable = "" if use_variable == placeholder else use_variable
filter_value = parse_filter_value(filter_value_text)

st.header("3. Coverage and placeholders")
eligibility = eligibility_table(data, profile, node_ids, country_variable, use_variable, factor_items, int(country_minimum_n))
st.dataframe(eligibility, width="stretch", hide_index=True)
st.caption("A placeholder is a deliberate, documented stop: it identifies the missing design or data requirement and avoids presenting a non-applicable Abadi et al. computation as if it had been executed.")

st.header("4. Create a reproducible run bundle")
project_title = st.text_input("Run title", key="project_title")
ready_core = bool((eligibility["Abadi-style computation"] == "Abadi joint mixed graphical network (MGM, LASSO/EBIC)").any() and (eligibility.loc[eligibility["Abadi-style computation"] == "Abadi joint mixed graphical network (MGM, LASSO/EBIC)", "Status"].iloc[0] == "Ready"))

if st.button("Create configuration and run bundle", type="primary"):
    provisional_dir = RUNS_DIR / "provisional"
    provisional_data_path = provisional_dir / "raw_data" / Path(uploaded.name).name
    provisional_config = build_config(
        run_dir=provisional_dir,
        data_path=provisional_data_path,
        sheet=sheet,
        project_title=project_title,
        study_design=study_design,
        node_mapping=node_mapping,
        node_type=node_type,
        levels=int(levels),
        filter_variable=filter_variable,
        filter_operator=filter_operator,
        filter_value=filter_value,
        country_variable=country_variable,
        use_variable=use_variable,
        categorical_variables=categorical_variables,
        factor_items=factor_items,
        country_minimum_n=int(country_minimum_n),
        quick_mode=quick_mode,
    )
    # Write a bundle using final paths, then regenerate configuration with final locations.
    temporary_dir = RUNS_DIR / f"temporary_{uuid.uuid4().hex[:8]}"
    temporary_dir.mkdir(parents=True, exist_ok=False)
    temporary_data_path = temporary_dir / "raw_data" / Path(uploaded.name).name
    final_config = build_config(
        run_dir=temporary_dir,
        data_path=temporary_data_path,
        sheet=sheet,
        project_title=project_title,
        study_design=study_design,
        node_mapping=node_mapping,
        node_type=node_type,
        levels=int(levels),
        filter_variable=filter_variable,
        filter_operator=filter_operator,
        filter_value=filter_value,
        country_variable=country_variable,
        use_variable=use_variable,
        categorical_variables=categorical_variables,
        factor_items=factor_items,
        country_minimum_n=int(country_minimum_n),
        quick_mode=quick_mode,
    )
    created_dir, created_config = write_run_bundle(file_bytes, uploaded.name, final_config, data)
    # Replace temporary absolute paths with actual run-directory paths.
    actual_data_path = created_dir / "raw_data" / Path(uploaded.name).name
    actual_config = build_config(
        run_dir=created_dir,
        data_path=actual_data_path,
        sheet=sheet,
        project_title=project_title,
        study_design=study_design,
        node_mapping=node_mapping,
        node_type=node_type,
        levels=int(levels),
        filter_variable=filter_variable,
        filter_operator=filter_operator,
        filter_value=filter_value,
        country_variable=country_variable,
        use_variable=use_variable,
        categorical_variables=categorical_variables,
        factor_items=factor_items,
        country_minimum_n=int(country_minimum_n),
        quick_mode=quick_mode,
    )
    created_config.write_text(yaml.safe_dump(actual_config, sort_keys=False, allow_unicode=True), encoding="utf-8")
    shutil.rmtree(temporary_dir, ignore_errors=True)
    st.session_state["run_dir"] = str(created_dir)
    st.session_state["config_path"] = str(created_config)
    st.success(f"Created run bundle: {created_dir.relative_to(ROOT)}")

if "config_path" in st.session_state:
    active_config = Path(st.session_state["config_path"])
    active_run = Path(st.session_state["run_dir"])
    st.code(str(active_config.relative_to(ROOT)), language="text")
    st.download_button("Download generated YAML configuration", data=active_config.read_bytes(), file_name="can_user_config.yml", mime="application/x-yaml")

    if not R_AVAILABLE:
        st.info("This deployment is running in mapping-only mode because no R runtime is available. You can upload data, map variables, inspect eligibility, and download a reproducible configuration. Run the analysis locally or on a container host with R and the required packages.")

    if st.button("Validate configuration with the R workflow", disabled=not R_AVAILABLE):
        with st.spinner("Running validation..."):
            return_code, output = invoke_r("validate_config.R", active_config)
        st.code(output or "No console output.", language="text")
        if return_code == 0:
            st.success("Configuration passed R-side validation.")
        else:
            st.error("R-side validation found an issue. Review the log above and adjust the mapping.")

    if ready_core:
        if st.button("Run core analysis (data audit, factor models, primary CAN network)", disabled=not R_AVAILABLE):
            with st.spinner("Running the core R workflow. Larger data and more nodes take longer."):
                return_code, output = invoke_r("run_core_analysis.R", active_config)
            (active_run / "core_analysis_console.log").write_text(output, encoding="utf-8")
            st.code(output[-12000:] or "No console output.", language="text")
            if return_code == 0:
                st.success("Core analysis completed. Outputs are inside the run bundle.")
            else:
                st.error("Core analysis did not complete. The console log and configuration remain available for debugging.")
    else:
        st.info("Core analysis is disabled until the joint-network eligibility row is Ready.")

    st.checkbox("I understand that full diagnostics and all pairwise country comparisons can be computationally intensive.", key="full_ack")
    if st.session_state.get("full_ack", False) and ready_core and st.button("Run full configured workflow", disabled=not R_AVAILABLE):
        with st.spinner("Running the complete configured workflow. This may take a substantial amount of time."):
            return_code, output = invoke_r("run_example.R", active_config)
        (active_run / "full_analysis_console.log").write_text(output, encoding="utf-8")
        st.code(output[-12000:] or "No console output.", language="text")
        if return_code == 0:
            st.success("Full configured workflow completed. Outputs are inside the run bundle.")
        else:
            st.error("The full workflow did not complete. Inspect the saved console log and module status files.")

st.divider()
st.caption("The app does not infer substantive theory from variable names. Users must map their own variables and labels to a CAN node set, select the study design when known, and use the eligibility table to identify unsupported or inapplicable computational steps.")
